name: Live Sync

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Call API
        run: |
          curl -H "Authorization: Bearer ${{ secrets.TOKEN }}" \
          "https://eg.me.logisticsbackoffice.com/api/kiwi/v1/couriers/attendance/city/1?page=0&search_worker_name=&size=10&sort_by=break_time&sort_direction=desc"
